id: "997d2c1393e3"
title: "Ingress NGINX: Statement from the Kubernetes Steering and Security Response Committees"
url: "https://kubernetes.io/blog/2026/01/29/ingress-nginx-statement/"
summary: "In March 2026, Kubernetes will retire Ingress NGINX, a piece of critical infrastructure for about half of cloud native environments. The retirement of Ingress NGINX was announced for March 2026, after years of public warnings that the project was in dire need of contributors and maintainers. There will be no more re..."
source: "kubernetes.io"
published_at: "2026-01-29T00:00:00Z"
created_at: "2026-02-07T19:58:14Z"
tags:
  - "platform-engineering"
  - "open-source"
  - "ai"
  - "developers"
  - "trending-tech"
  - "technology"
